server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/MiniProjDB'
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  mail:
    host: smtp.gmail.com
    username: madhadisuman@gmail.com
    password: gfduhxofgxmajgcr
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
